=== nanreh/calendar-hack/public/schema/plan-schema.json
{
    "description": "Plan schema",
    "$id": "https://defy.org/plan",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15k/10m",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {"type": "number"},
                "tags": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "Rest",
                            "Easy Run",
                            "Run",
                            "Long Run",
                            "Cross Train",
                            "Race",
                            "Speedwork",
                            "Hills"
                        ]
                    },
                    "minItems": 1,
                    "uniqueItems": true
                }
            },
            "required": [
                "title"
            ]
        }
    }
}

=== nanreh/calendar-hack/public/plans/json/frr_bt_02.json
{
   "id": "frr_bb_02",
   "name": "Faster Road Racing: Base Building Schedule 2",
   "description": "\"Base Training 2: Building up to 45 Miles (72 km) per Week\" from \"Faster Road Racing: 5K to Half Marathon\" by Pete D. Pfitzinger and Philip Latter.\"",
   "units": "mi",
   "source": "https://www.amazon.com/Faster-Road-Racing-Half-Marathon/dp/1450470459",
   "type": "Base",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{5:9}",
               "distance": 5.0
            },
            {
               "title": "Endurance\n{9:14}",
               "distance": 9.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic + speed {6} w/ 8 x 100 m strides\n{6:10}",
               "distance": 6.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "Endurance\n{10:16}",
               "distance": 10.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "Lactate threshold\n{7:11}\n18 min tempo run",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "General aerobic\n{3:5}",
               "distance": 3.0
            },
            {
               "title": "General aerobic + speed {7} w/ 8 x 100 m strides\n{7:11}",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Lactate threshold\n{8:13}\n20 min tempo run",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Endurance\n{11:18}",
               "distance": 11.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides\n{8:13}",
               "distance": 7.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "General aerobic\n{4:6}",
               "distance": 4.0
            },
            {
               "title": "Lactate threshold\n{8:13}\n22 min tempo run",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{9:14}",
               "distance": 9.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{10:16}",
               "distance": 10.0
            },
            {
               "title": "General aerobic\n{5:8}",
               "distance": 4.0
            },
            {
               "title": "General aerobic + speed {8} w/ 8 x 100 m strides\n{8:13}",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-training"
            },
            {
               "title": "General aerobic\n{10:16}",
               "distance": 10.0
            },
            {
               "title": "Endurance\n{12:19}",
               "distance": 12.0
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_more_than_85_recovery_4th.json
{
   "id": "pfitz_more_than_85_recovery_4th",
   "name": "Pfitzinger/Douglas: Marathon More Than 85 Miles per Week Recovery",
   "description": "\"More Than 85 Miles per Week Recovery: Training Block 5 - Recovery\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {8:13}",
               "distance": 8
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {7:11}",
               "distance": 7
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5
            },
            {
               "title": "Gen-aerobic {10:16}",
               "distance": 10
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Recovery {7:11}",
               "distance": 7
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 8 x 100 m strides",
               "distance": 8
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Gen-aerobic {10:16}",
               "distance": 10
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {9:14} with 8 x 100 m strides",
               "distance": 9
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long {12:19}",
               "distance": 12
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Gen-aerobic {8:13}",
               "distance": 8
            },
            {
               "title": "Gen-aerobic + speed {10:16} with 10 x 100 m strides",
               "distance": 10
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {10:16} with {4:6} at LT pace",
               "distance": 10
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6
            },
            {
               "title": "Med-long {14:23}",
               "distance": 14
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_12_55.json
{
   "id": "pfitz_12_55",
   "name": "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule",
   "description": "\"Up to 55 miles per week, 12-week schedule\" from \"Advanced Marathoning\" (third edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/gp/product/149256866X/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 x 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic {9:14}",
               "distance": 9.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Marathon-pace run {13:21} with {8:13} at marathon pace",
               "distance": 13.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {8:13} with {4:6} at LT pace",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Med-long run {15:24}",
               "distance": 15.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {8:13} with 6 x 10 sec hill sprints + 8 X 100 m strides",
               "distance": 8.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Marathon-pace run {16:26} with {10:16} at marathon pace",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "LT {10:16} with {5:8} at LT pace",
               "distance": 10.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {9:14} with {4:6} at LT pace",
               "distance": 9.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {16:26}",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "VO\u2082max {10:16} with 5 x 1,000 m at 5K race pace; jog 50-90% interval time",
               "distance": 10.0
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Marathon-pace run {15:24} with {12:19} at marathon pace",
               "distance": 15.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6:10} with 6 x 100 m strides",
               "distance": 6.0
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "LT {12:19} with {7:11} at LT pace",
               "distance": 12.0
            },
            {
               "title": "Recovery {5:8}",
               "distance": 5.0
            },
            {
               "title": "Long run {20:32}",
               "distance": 20.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO\u2082max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4.0
            },
            {
               "title": "8K-15K tune-up race (total 9-13 miles [14-21 km])",
               "distance": 9.0
            },
            {
               "title": "Long run {17:27}",
               "distance": 17.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 6 x 100 m strides",
               "distance": 7.0
            },
            {
               "title": "VO\u2082max {10:16} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 10.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {11:18}",
               "distance": 11.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Long run {20:32}",
               "distance": 20.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "VO\u2082max {8:13} with 5 x 600 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {4:6} with 6 x 100 m strides",
               "distance": 4.0
            },
            {
               "title": "8K-10K tune-up race (total 9-11 miles [14-18 km])",
               "distance": 9.0
            },
            {
               "title": "Long run {16:26}",
               "distance": 16.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {7:11} with 8 x 100 m strides",
               "distance": 7.0
            },
            {
               "title": "VO\u2082max {8:13} with 4 x 1,200 m at 5K race pace; jog 50-90% interval time",
               "distance": 8.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Med-long run {12:19}",
               "distance": 12.0
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {6:10}",
               "distance": 6.0
            },
            {
               "title": "Dress rehearsal {7:11} with {2:3} at marathon pace",
               "distance": 7.0
            },
            {
               "title": "Rest"
            },
            {
               "title": "Recovery + speed {5:8} with 6 x 100 m strides",
               "distance": 5.0
            },
            {
               "title": "Recovery {4:6}",
               "distance": 4.0
            },
            {
               "title": "Plan Ends",
               "distance": 26.2
            }
         ]
      }
   ]
}
