=== nanreh/calendar-hack/public/schema/plan-schema-v1.json
{
    "description": "Plan schema v1",
    "$id": "https://defy.org/plan/v1",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "schemaVersion": {
            "type": "integer",
            "const": 1
        },
        "id": {
            "type": "string",
            "pattern": "^[a-z0-9]+(?:_[a-z0-9]+)*$"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "type": {
            "enum": [
                "Base",
                "Multiple Distances",
                "Marathon",
                "Half Marathon",
                "5K",
                "10K",
                "15k/10m",
                "50K",
                "100K",
                "100M"
            ]
        },
        "units": {
            "enum": [
                "mi",
                "km"
            ]
        },
        "source": {
            "type": "string"
        },
        "schedule": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/week"
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "description",
        "units",
        "source",
        "type",
        "schedule"
    ],
    "definitions": {
        "week": {
            "type": "object",
            "properties": {
                "description": {"type": "string"},
                "workouts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workout"
                    },
                    "minItems": 7,
                    "maxItems": 7
                }
            },
            "required": [
                "workouts"
            ]
        },
        "workout": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "distance": {
                    "anyOf": [
                      { "type": "number" },
                      {
                        "type": "array",
                        "items": { "type": "number" },
                        "minItems": 1,
                        "maxItems": 2
                      }
                    ]
                  }
            },
            "required": [
                "title"
            ]
        }
    }
}

=== nanreh/calendar-hack/public/plans/json/pfitz_70_recovery_4th.json
{
   "id": "pfitz_70_recovery_4th",
   "name": "Pfitzinger/Douglas: Marathon 55 to 70 Miles per Week Recovery",
   "description": "\"55 to 70 Miles per Week Recovery: Training Block 5 - Recovery\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {3-4:5-6}",
               "distance": [
                  3.0,
                  4.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {4-6:6-10}",
               "distance": [
                  4.0,
                  6.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic {7-8:11-13}",
               "distance": [
                  7.0,
                  8.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 \u00d7 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Gen-aerobic {8-9:13-14}",
               "distance": [
                  8.0,
                  9.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Med-long run {10-11:16-18}",
               "distance": [
                  10.0,
                  11.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Rest or cross-train",
               "distance": [
                  0.0,
                  0.0
               ]
            },
            {
               "title": "Gen-aerobic + speed {8-9:13-14} with 8 \u00d7 100 m strides",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Med-long run {11-13:18-21}",
               "distance": [
                  11.0,
                  13.0
               ]
            }
         ]
      }
   ]
}

=== nanreh/calendar-hack/public/plans/json/pfitz_06_multi_4th.json
{
   "id": "pfitz_06_multi_4th",
   "name": "Pfitzinger/Douglas: Multiple Marathoning, 6-week schedule",
   "description": "\"Multiple Marathoning, 6-week schedule\" from \"Advanced Marathoning\" (fourth edition) by Pete Pfitzinger and Scott Douglas",
   "units": "mi",
   "source": "https://www.amazon.com/dp/1718237472/",
   "type": "Marathon",
   "schedule": [
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {6-7:10-11}",
               "distance": [
                  6.0,
                  7.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {7-8:11-13}",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 x 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Gen-aerobic + speed {7-8:11-13} with 8 x 100 m strides",
               "distance": [
                  7.0,
                  8.0
               ]
            },
            {
               "title": "Med-long run {11-12:18-19}",
               "distance": [
                  11.0,
                  12.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Med-long run {13-14:21-23}",
               "distance": [
                  13.0,
                  14.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Gen-aerobic {9-10:14-16}",
               "distance": [
                  9.0,
                  10.0
               ]
            },
            {
               "title": "Recovery + speed {5-6:8-10} with 6 x 100 m strides",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "8K-10K tune-up race (total {10-12:16-19})",
               "distance": [
                  10.0,
                  12.0
               ]
            },
            {
               "title": "Long run {16-17:26-27}",
               "distance": [
                  16.0,
                  17.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest or cross-train"
            },
            {
               "title": "Recovery + speed {6-7:10-11} with 8 x 100 m strides",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "V\u0307O\u2082max {8-9:13-14} with 6 x 600 m at 5K race pace; jog 50%-90% interval time",
               "distance": [
                  8.0,
                  9.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery + speed {6-7:10-11} with 8 x 100 m strides",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Med-long run {12-13:19-21}",
               "distance": [
                  12.0,
                  13.0
               ]
            }
         ]
      },
      {
         "workouts": [
            {
               "title": "Rest"
            },
            {
               "title": "Recovery {5-6:8-10}",
               "distance": [
                  5.0,
                  6.0
               ]
            },
            {
               "title": "Dress rehearsal {6-7:10-11} with {2:3} at marathon pace",
               "distance": [
                  6.0,
                  7.0
               ]
            },
            {
               "title": "Recovery {4-5:6-8}",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery + speed {4-5:6-8} with 6 x 100 m strides",
               "distance": [
                  4.0,
                  5.0
               ]
            },
            {
               "title": "Recovery {2-4:3-6}",
               "distance": [
                  2.0,
                  4.0
               ]
            },
            {
               "title": "Second marathon",
               "distance": 26.2
            }
         ]
      }
   ]
}
